

all : listing1 listing7 listing9 listing10 \
listing11


listing1 : listing1.cpp
	g++ -o listing1 listing1.cpp

listing7 : listing7.cpp
	g++ -o listing7 listing7.cpp

listing9 : listing9.cpp
	g++ -o listing9 listing9.cpp

listing10 : listing10.cpp
	g++ -o listing10 listing10.cpp

listing11 : listing11.cpp
	g++ -o listing11 listing11.cpp


clean :
	rm -f listing1
	rm -f listing7
	rm -f listing9
	rm -f listing10
	rm -f listing11

